base_url = "https://mattwestrik.com"
title = "Matt Westrik - Software Engineer"

compile_sass = true
build_search_index = true
#minify_html = true # this breaks line-breaks in code blocks
generate_feed = true
taxonomies = [
  {name = "tags"}, # feed = true
  {name = "categories", paginate_by = 5}, # feed = true
]

[markdown]
highlight_code = true
highlight_theme = "solarized-dark"
render_emoji = true
smart_punctuation = true
# external_links_target_blank = true

[extra]
